<?php

namespace ContainerRyXp5ka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JUvKOz0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jUvKOz0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jUvKOz0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'materiellocation' => ['privates', '.errored..service_locator.jUvKOz0.App\\Entity\\Materiellocation', NULL, 'Cannot autowire service ".service_locator.jUvKOz0": it needs an instance of "App\\Entity\\Materiellocation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'materiellocation' => 'App\\Entity\\Materiellocation',
        ]);
    }
}
