<?php

namespace ContainerRyXp5ka;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_Orm_ListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_translation.orm.listener' shared service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Storage\Listener\DoctrineORMListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Storage'.\DIRECTORY_SEPARATOR.'Listener'.\DIRECTORY_SEPARATOR.'DoctrineORMListener.php';

        return $container->privates['lexik_translation.orm.listener'] = new \Lexik\Bundle\TranslationBundle\Storage\Listener\DoctrineORMListener();
    }
}
