<?php

namespace Container4IxSCym;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielventeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kbe5N4e.App\Entity\Materielvente' shared service.
     *
     * @return \App\Entity\Materielvente
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.kbe5N4e": it needs an instance of "App\\Entity\\Materielvente" but this type has been excluded in "config/services.yaml".');
    }
}
