<?php

namespace ContainerVxMKZfx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SesXeknService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sesXekn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sesXekn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\MaterielController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MaterielController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MateriellocationController::delete' => ['privates', '.service_locator.qAUb40R', 'get_ServiceLocator_QAUb40RService', true],
            'App\\Controller\\MateriellocationController::edit' => ['privates', '.service_locator.qAUb40R', 'get_ServiceLocator_QAUb40RService', true],
            'App\\Controller\\MateriellocationController::index' => ['privates', '.service_locator.cf8iMp4', 'get_ServiceLocator_Cf8iMp4Service', true],
            'App\\Controller\\MateriellocationController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MateriellocationController::show' => ['privates', '.service_locator.jUvKOz0', 'get_ServiceLocator_JUvKOz0Service', true],
            'App\\Controller\\MaterielventeController::delete' => ['privates', '.service_locator.wZGs69i', 'get_ServiceLocator_WZGs69iService', true],
            'App\\Controller\\MaterielventeController::edit' => ['privates', '.service_locator.wZGs69i', 'get_ServiceLocator_WZGs69iService', true],
            'App\\Controller\\MaterielventeController::index' => ['privates', '.service_locator.52Vt23p', 'get_ServiceLocator_52Vt23pService', true],
            'App\\Controller\\MaterielventeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaterielventeController::show' => ['privates', '.service_locator.kbe5N4e', 'get_ServiceLocator_Kbe5N4eService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\MaterielController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MaterielController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\MateriellocationController:delete' => ['privates', '.service_locator.qAUb40R', 'get_ServiceLocator_QAUb40RService', true],
            'App\\Controller\\MateriellocationController:edit' => ['privates', '.service_locator.qAUb40R', 'get_ServiceLocator_QAUb40RService', true],
            'App\\Controller\\MateriellocationController:index' => ['privates', '.service_locator.cf8iMp4', 'get_ServiceLocator_Cf8iMp4Service', true],
            'App\\Controller\\MateriellocationController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MateriellocationController:show' => ['privates', '.service_locator.jUvKOz0', 'get_ServiceLocator_JUvKOz0Service', true],
            'App\\Controller\\MaterielventeController:delete' => ['privates', '.service_locator.wZGs69i', 'get_ServiceLocator_WZGs69iService', true],
            'App\\Controller\\MaterielventeController:edit' => ['privates', '.service_locator.wZGs69i', 'get_ServiceLocator_WZGs69iService', true],
            'App\\Controller\\MaterielventeController:index' => ['privates', '.service_locator.52Vt23p', 'get_ServiceLocator_52Vt23pService', true],
            'App\\Controller\\MaterielventeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MaterielventeController:show' => ['privates', '.service_locator.kbe5N4e', 'get_ServiceLocator_Kbe5N4eService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\MaterielController::index' => '?',
            'App\\Controller\\MaterielController::new' => '?',
            'App\\Controller\\MateriellocationController::delete' => '?',
            'App\\Controller\\MateriellocationController::edit' => '?',
            'App\\Controller\\MateriellocationController::index' => '?',
            'App\\Controller\\MateriellocationController::new' => '?',
            'App\\Controller\\MateriellocationController::show' => '?',
            'App\\Controller\\MaterielventeController::delete' => '?',
            'App\\Controller\\MaterielventeController::edit' => '?',
            'App\\Controller\\MaterielventeController::index' => '?',
            'App\\Controller\\MaterielventeController::new' => '?',
            'App\\Controller\\MaterielventeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\MaterielController:index' => '?',
            'App\\Controller\\MaterielController:new' => '?',
            'App\\Controller\\MateriellocationController:delete' => '?',
            'App\\Controller\\MateriellocationController:edit' => '?',
            'App\\Controller\\MateriellocationController:index' => '?',
            'App\\Controller\\MateriellocationController:new' => '?',
            'App\\Controller\\MateriellocationController:show' => '?',
            'App\\Controller\\MaterielventeController:delete' => '?',
            'App\\Controller\\MaterielventeController:edit' => '?',
            'App\\Controller\\MaterielventeController:index' => '?',
            'App\\Controller\\MaterielventeController:new' => '?',
            'App\\Controller\\MaterielventeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
