<?php

namespace ContainerOiRB478;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuthSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\OAuthSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\OAuthSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'OAuthSuccessListener.php';

        return $container->privates['App\\EventListener\\OAuthSuccessListener'] = new \App\EventListener\OAuthSuccessListener(($container->services['router'] ?? self::getRouterService($container)));
    }
}
