<?php

namespace ContainerUTIFZ6w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_Form_Handler_TransUnitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_translation.form.handler.trans_unit' shared autowired service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Form\Handler\TransUnitFormHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'FormHandlerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'TransUnitFormHandler.php';

        return $container->services['lexik_translation.form.handler.trans_unit'] = new \Lexik\Bundle\TranslationBundle\Form\Handler\TransUnitFormHandler(($container->services['lexik_translation.trans_unit.manager'] ?? $container->load('getLexikTranslation_TransUnit_ManagerService')), ($container->privates['lexik_translation.file.manager'] ?? $container->load('getLexikTranslation_File_ManagerService')), ($container->services['lexik_translation.translation_storage'] ?? $container->load('getLexikTranslation_TranslationStorageService')), ($container->services['Lexik\\Bundle\\TranslationBundle\\Manager\\LocaleManager'] ?? $container->load('getLocaleManagerService')), \dirname(__DIR__, 4));
    }
}
