<?php

namespace ContainerUTIFZ6w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_File_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'lexik_translation.file.manager' shared service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Manager\FileManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Manager'.\DIRECTORY_SEPARATOR.'FileManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Manager'.\DIRECTORY_SEPARATOR.'FileManager.php';

        return $container->privates['lexik_translation.file.manager'] = new \Lexik\Bundle\TranslationBundle\Manager\FileManager(($container->services['lexik_translation.translation_storage'] ?? $container->load('getLexikTranslation_TranslationStorageService')), \dirname(__DIR__, 4));
    }
}
