<?php

namespace ContainerUTIFZ6w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_DataGrid_FormatterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_translation.data_grid.formatter' shared service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Util\DataGrid\DataGridFormatter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'DataGrid'.\DIRECTORY_SEPARATOR.'DataGridFormatter.php';

        return $container->services['lexik_translation.data_grid.formatter'] = new \Lexik\Bundle\TranslationBundle\Util\DataGrid\DataGridFormatter(($container->services['Lexik\\Bundle\\TranslationBundle\\Manager\\LocaleManager'] ?? $container->load('getLocaleManagerService')), 'orm');
    }
}
