<?php

namespace ContainerUTIFZ6w;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_Overview_StatsAggregatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_translation.overview.stats_aggregator' shared service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Util\Overview\StatsAggregator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'Overview'.\DIRECTORY_SEPARATOR.'StatsAggregator.php';

        return $container->services['lexik_translation.overview.stats_aggregator'] = new \Lexik\Bundle\TranslationBundle\Util\Overview\StatsAggregator(($container->services['lexik_translation.translation_storage'] ?? $container->load('getLexikTranslation_TranslationStorageService')), ($container->services['Lexik\\Bundle\\TranslationBundle\\Manager\\LocaleManager'] ?? $container->load('getLocaleManagerService')));
    }
}
