hwi_oauth:
    firewall_names: [main, admin]
    resource_owners:
        google:
            type:                google
            client_id:           '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret:       '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            scope:               "email profile"
            redirect_uri:        '%env(OAUTH_GOOGLE_REDIRECT_URI)%'
