liip_imagine:
    driver: "gd" # ou "imagick" si tu as Imagick installé
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    filter_sets:
        thumbnail:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
