twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    paths: ['%kernel.project_dir%/templates']
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_name: 'YourApp'

when@test:
    twig:
        strict_variables: true
