<?php

namespace ContainerTi8QHbN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOAuth2ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\OAuth2Controller' shared autowired service.
     *
     * @return \App\Controller\OAuth2Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'OAuth2Controller.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'OAuth2'.\DIRECTORY_SEPARATOR.'GoogleProvider.php';

        $container->services['App\\Controller\\OAuth2Controller'] = $instance = new \App\Controller\OAuth2Controller(new \App\Security\OAuth2\GoogleProvider(($container->services['router'] ?? self::getRouterService($container))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\OAuth2Controller', $container));

        return $instance;
    }
}
