<?php

namespace ContainerQFwuP4F;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserStatisticsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\UserStatisticsService' shared autowired service.
     *
     * @return \App\Service\UserStatisticsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UserStatisticsService.php';

        return $container->services['App\\Service\\UserStatisticsService'] = new \App\Service\UserStatisticsService(($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
