<?php

namespace ContainerCxGgP8J;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_XGXVDN_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.xGXVDN.' shared service.
     *
     * @return \App\Controller\YousignService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ContratController::signature()": the $yousignService argument is type-hinted with the non-existent class or interface: "App\\Controller\\YousignService". Did you forget to add a use statement?');
    }
}
