<?php

namespace ContainerRwuYcXE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W8I1kFTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w8I1kFT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w8I1kFT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\ParcelleProprietesRepository', 'getParcelleProprietesRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\ParcelleProprietesRepository',
        ]);
    }
}
