<?php

namespace ContainerRwuYcXE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YCl_0rEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yCl.0rE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yCl.0rE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contrat' => ['privates', '.errored..service_locator.yCl.0rE.App\\Entity\\Contrat', NULL, 'Cannot autowire service ".service_locator.yCl.0rE": it needs an instance of "App\\Entity\\Contrat" but this type has been excluded in "config/services.yaml".'],
            'contratRepository' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'yousignService' => ['privates', '.errored.xGXVDN.', NULL, 'Cannot determine controller argument for "App\\Controller\\ContratController::signature()": the $yousignService argument is type-hinted with the non-existent class or interface: "App\\Controller\\YousignService". Did you forget to add a use statement?'],
        ], [
            'contrat' => 'App\\Entity\\Contrat',
            'contratRepository' => 'App\\Repository\\ContratRepository',
            'entityManager' => '?',
            'yousignService' => '?',
        ]);
    }
}
