<?php

namespace ContainerRwuYcXE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContrat4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yCl.0rE.App\Entity\Contrat' shared service.
     *
     * @return \App\Entity\Contrat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yCl.0rE": it needs an instance of "App\\Entity\\Contrat" but this type has been excluded in "config/services.yaml".');
    }
}
