<?php

namespace ContainerWM11mhy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGnQZAqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WGnQZAq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WGnQZAq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'offre' => ['privates', '.errored..service_locator.WGnQZAq.App\\Entity\\Offre', NULL, 'Cannot autowire service ".service_locator.WGnQZAq": it needs an instance of "App\\Entity\\Offre" but this type has been excluded in "config/services.yaml".'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'client' => '?',
            'entityManager' => '?',
            'offre' => 'App\\Entity\\Offre',
            'security' => '?',
        ]);
    }
}
