<?php

namespace Container48xepVm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportTranslationsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'console.command.public_alias.Lexik\Bundle\TranslationBundle\Command\ExportTranslationsCommand' shared autowired service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Command\ExportTranslationsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'ExportTranslationsCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'filesystem'.\DIRECTORY_SEPARATOR.'Filesystem.php';

        return $container->services['console.command.public_alias.Lexik\\Bundle\\TranslationBundle\\Command\\ExportTranslationsCommand'] = new \Lexik\Bundle\TranslationBundle\Command\ExportTranslationsCommand(($container->services['lexik_translation.translation_storage'] ?? $container->load('getLexikTranslation_TranslationStorageService')), ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), ($container->services['lexik_translation.exporter_collector'] ?? $container->load('getLexikTranslation_ExporterCollectorService')), \dirname(__DIR__, 4));
    }
}
