<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUTIFZ6w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUTIFZ6w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUTIFZ6w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUTIFZ6w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUTIFZ6w\App_KernelDevDebugContainer([
    'container.build_hash' => 'UTIFZ6w',
    'container.build_id' => '82f0a84c',
    'container.build_time' => 1741053323,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUTIFZ6w');
