<?php

namespace ContainerFfxRxfL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RWq9sr7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RWq9sr7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RWq9sr7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AdminController::deleteProduct' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::deleteProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::deleteStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::editProduct' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\AdminController::editProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::editStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::exportDashboardReport' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::exportFullReport' => ['privates', '.service_locator.844qzXl', 'get_ServiceLocator_844qzXlService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::newProduct' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\AdminController::newProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::newStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::productTypes' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::products' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController::stocks' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController::productQR' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController::shop' => ['privates', '.service_locator.lVF54df', 'get_ServiceLocator_LVF54dfService', true],
            'App\\Controller\\PageController::shopDetail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AdminController:deleteProduct' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:deleteProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:deleteStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:editProduct' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\AdminController:editProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:editStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:exportDashboardReport' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:exportFullReport' => ['privates', '.service_locator.844qzXl', 'get_ServiceLocator_844qzXlService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:newProduct' => ['privates', '.service_locator.LNwsF6h', 'get_ServiceLocator_LNwsF6hService', true],
            'App\\Controller\\AdminController:newProductType' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:newStock' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:productTypes' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:products' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AdminController:stocks' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController:productQR' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PageController:shop' => ['privates', '.service_locator.lVF54df', 'get_ServiceLocator_LVF54dfService', true],
            'App\\Controller\\PageController:shopDetail' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AdminController::deleteProduct' => '?',
            'App\\Controller\\AdminController::deleteProductType' => '?',
            'App\\Controller\\AdminController::deleteStock' => '?',
            'App\\Controller\\AdminController::editProduct' => '?',
            'App\\Controller\\AdminController::editProductType' => '?',
            'App\\Controller\\AdminController::editStock' => '?',
            'App\\Controller\\AdminController::exportDashboardReport' => '?',
            'App\\Controller\\AdminController::exportFullReport' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::newProduct' => '?',
            'App\\Controller\\AdminController::newProductType' => '?',
            'App\\Controller\\AdminController::newStock' => '?',
            'App\\Controller\\AdminController::productTypes' => '?',
            'App\\Controller\\AdminController::products' => '?',
            'App\\Controller\\AdminController::stocks' => '?',
            'App\\Controller\\PageController::productQR' => '?',
            'App\\Controller\\PageController::shop' => '?',
            'App\\Controller\\PageController::shopDetail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:deleteProduct' => '?',
            'App\\Controller\\AdminController:deleteProductType' => '?',
            'App\\Controller\\AdminController:deleteStock' => '?',
            'App\\Controller\\AdminController:editProduct' => '?',
            'App\\Controller\\AdminController:editProductType' => '?',
            'App\\Controller\\AdminController:editStock' => '?',
            'App\\Controller\\AdminController:exportDashboardReport' => '?',
            'App\\Controller\\AdminController:exportFullReport' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:newProduct' => '?',
            'App\\Controller\\AdminController:newProductType' => '?',
            'App\\Controller\\AdminController:newStock' => '?',
            'App\\Controller\\AdminController:productTypes' => '?',
            'App\\Controller\\AdminController:products' => '?',
            'App\\Controller\\AdminController:stocks' => '?',
            'App\\Controller\\PageController:productQR' => '?',
            'App\\Controller\\PageController:shop' => '?',
            'App\\Controller\\PageController:shopDetail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
