<?php

namespace ContainerFfxRxfL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQRCodeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QRCodeService' shared autowired service.
     *
     * @return \App\Service\QRCodeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QRCodeService.php';

        return $container->privates['App\\Service\\QRCodeService'] = new \App\Service\QRCodeService(($container->services['router'] ?? self::getRouterService($container)));
    }
}
