<?php

namespace ContainerDU5uLlq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getYousignServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\YousignService' shared autowired service.
     *
     * @return \App\Service\YousignService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'YousignService.php';

        $a = ($container->privates['App\\Service\\PdfGeneratorService'] ?? $container->load('getPdfGeneratorServiceService'));

        if (isset($container->privates['App\\Service\\YousignService'])) {
            return $container->privates['App\\Service\\YousignService'];
        }

        return $container->privates['App\\Service\\YousignService'] = new \App\Service\YousignService(($container->privates['.debug.yousign.client'] ?? self::get_Debug_Yousign_ClientService($container)), $a);
    }
}
