<?php

namespace ContainerRXuPd1O;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0d1vtYtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0d1vtYt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0d1vtYt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CommandeController::delete' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController::edit' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.RXaRRrV', 'get_ServiceLocator_RXaRRrVService', true],
            'App\\Controller\\CommandeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController::show' => ['privates', '.service_locator.TqIg1ou', 'get_ServiceLocator_TqIg1ouService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CommandeController:delete' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController:edit' => ['privates', '.service_locator.iR5i4O4', 'get_ServiceLocator_IR5i4O4Service', true],
            'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.RXaRRrV', 'get_ServiceLocator_RXaRRrVService', true],
            'App\\Controller\\CommandeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CommandeController:show' => ['privates', '.service_locator.TqIg1ou', 'get_ServiceLocator_TqIg1ouService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CommandeController::delete' => '?',
            'App\\Controller\\CommandeController::edit' => '?',
            'App\\Controller\\CommandeController::index' => '?',
            'App\\Controller\\CommandeController::new' => '?',
            'App\\Controller\\CommandeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CommandeController:delete' => '?',
            'App\\Controller\\CommandeController:edit' => '?',
            'App\\Controller\\CommandeController:index' => '?',
            'App\\Controller\\CommandeController:new' => '?',
            'App\\Controller\\CommandeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
