<?php

namespace ContainerMrJcCi4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RpiXYCOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rpiXYCO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rpiXYCO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'paginator' => ['privates', '.errored.FJIt_v6', NULL, 'Cannot determine controller argument for "App\\Controller\\CommandeController::index()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Bundle\\PaginatorBundle\\KnpPaginatorInterface".'],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'paginator' => '?',
        ]);
    }
}
