<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProductType extends \App\Entity\ProductType implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'harvest_date' => [parent::class, 'harvest_date', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'preservation_duration' => [parent::class, 'preservation_duration', null],
        "\0".parent::class."\0".'production_method' => [parent::class, 'production_method', null],
        "\0".parent::class."\0".'season' => [parent::class, 'season', null],
        'harvest_date' => [parent::class, 'harvest_date', null],
        'id' => [parent::class, 'id', null],
        'preservation_duration' => [parent::class, 'preservation_duration', null],
        'production_method' => [parent::class, 'production_method', null],
        'season' => [parent::class, 'season', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
