<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'commandes' => [parent::class, 'commandes', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'employes' => [parent::class, 'employes', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'materiellocations' => [parent::class, 'materiellocations', null],
        "\0".parent::class."\0".'materielventes' => [parent::class, 'materielventes', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'parcelleProprietes' => [parent::class, 'parcelleProprietes', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'avatar' => [parent::class, 'avatar', null],
        'commandes' => [parent::class, 'commandes', null],
        'email' => [parent::class, 'email', null],
        'employes' => [parent::class, 'employes', null],
        'id' => [parent::class, 'id', null],
        'materiellocations' => [parent::class, 'materiellocations', null],
        'materielventes' => [parent::class, 'materielventes', null],
        'nom' => [parent::class, 'nom', null],
        'parcelleProprietes' => [parent::class, 'parcelleProprietes', null],
        'password' => [parent::class, 'password', null],
        'prenom' => [parent::class, 'prenom', null],
        'roles' => [parent::class, 'roles', null],
        'telephone' => [parent::class, 'telephone', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
