<?php

namespace ContainerYVCl4qz;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Umuhvu1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.umuhvu1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.umuhvu1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'parcellePropriete' => ['privates', '.errored..service_locator.umuhvu1.App\\Entity\\ParcelleProprietes', NULL, 'Cannot autowire service ".service_locator.umuhvu1": it needs an instance of "App\\Entity\\ParcelleProprietes" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mailer' => '?',
            'parcellePropriete' => 'App\\Entity\\ParcelleProprietes',
        ]);
    }
}
