<?php

namespace ContainerGJ6igsF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLexikTranslation_TransUnit_ManagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'lexik_translation.trans_unit.manager' shared service.
     *
     * @return \Lexik\Bundle\TranslationBundle\Manager\TransUnitManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Manager'.\DIRECTORY_SEPARATOR.'TransUnitManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'lexik'.\DIRECTORY_SEPARATOR.'translation-bundle'.\DIRECTORY_SEPARATOR.'Manager'.\DIRECTORY_SEPARATOR.'TransUnitManager.php';

        return $container->services['lexik_translation.trans_unit.manager'] = new \Lexik\Bundle\TranslationBundle\Manager\TransUnitManager(($container->services['lexik_translation.translation_storage'] ?? $container->load('getLexikTranslation_TranslationStorageService')), ($container->privates['lexik_translation.file.manager'] ?? $container->load('getLexikTranslation_File_ManagerService')), \dirname(__DIR__, 4));
    }
}
