<?php

namespace ContainerR39kf86;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O5rBxd_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o5rBxd.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o5rBxd.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ContratController::delete' => ['privates', '.service_locator.0d0FLAy', 'get_ServiceLocator_0d0FLAyService', true],
            'App\\Controller\\ContratController::edit' => ['privates', '.service_locator.0d0FLAy', 'get_ServiceLocator_0d0FLAyService', true],
            'App\\Controller\\ContratController::index' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\ContratController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ContratController::show' => ['privates', '.service_locator.xpZJLkN', 'get_ServiceLocator_XpZJLkNService', true],
            'App\\Controller\\ParcelleProprietesController::delete' => ['privates', '.service_locator.IU.QoY9', 'get_ServiceLocator_IU_QoY9Service', true],
            'App\\Controller\\ParcelleProprietesController::edit' => ['privates', '.service_locator.IU.QoY9', 'get_ServiceLocator_IU_QoY9Service', true],
            'App\\Controller\\ParcelleProprietesController::index' => ['privates', '.service_locator.vs9Bn8g', 'get_ServiceLocator_Vs9Bn8gService', true],
            'App\\Controller\\ParcelleProprietesController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParcelleProprietesController::show' => ['privates', '.service_locator.j.H5nS2', 'get_ServiceLocator_J_H5nS2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ContratController:delete' => ['privates', '.service_locator.0d0FLAy', 'get_ServiceLocator_0d0FLAyService', true],
            'App\\Controller\\ContratController:edit' => ['privates', '.service_locator.0d0FLAy', 'get_ServiceLocator_0d0FLAyService', true],
            'App\\Controller\\ContratController:index' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\ContratController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ContratController:show' => ['privates', '.service_locator.xpZJLkN', 'get_ServiceLocator_XpZJLkNService', true],
            'App\\Controller\\ParcelleProprietesController:delete' => ['privates', '.service_locator.IU.QoY9', 'get_ServiceLocator_IU_QoY9Service', true],
            'App\\Controller\\ParcelleProprietesController:edit' => ['privates', '.service_locator.IU.QoY9', 'get_ServiceLocator_IU_QoY9Service', true],
            'App\\Controller\\ParcelleProprietesController:index' => ['privates', '.service_locator.vs9Bn8g', 'get_ServiceLocator_Vs9Bn8gService', true],
            'App\\Controller\\ParcelleProprietesController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParcelleProprietesController:show' => ['privates', '.service_locator.j.H5nS2', 'get_ServiceLocator_J_H5nS2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ContratController::delete' => '?',
            'App\\Controller\\ContratController::edit' => '?',
            'App\\Controller\\ContratController::index' => '?',
            'App\\Controller\\ContratController::new' => '?',
            'App\\Controller\\ContratController::show' => '?',
            'App\\Controller\\ParcelleProprietesController::delete' => '?',
            'App\\Controller\\ParcelleProprietesController::edit' => '?',
            'App\\Controller\\ParcelleProprietesController::index' => '?',
            'App\\Controller\\ParcelleProprietesController::new' => '?',
            'App\\Controller\\ParcelleProprietesController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ContratController:delete' => '?',
            'App\\Controller\\ContratController:edit' => '?',
            'App\\Controller\\ContratController:index' => '?',
            'App\\Controller\\ContratController:new' => '?',
            'App\\Controller\\ContratController:show' => '?',
            'App\\Controller\\ParcelleProprietesController:delete' => '?',
            'App\\Controller\\ParcelleProprietesController:edit' => '?',
            'App\\Controller\\ParcelleProprietesController:index' => '?',
            'App\\Controller\\ParcelleProprietesController:new' => '?',
            'App\\Controller\\ParcelleProprietesController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
