<?php

namespace ContainerZxuHqXe;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCvhlFhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rCvhlFh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rCvhlFh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'employe' => ['privates', '.errored..service_locator.rCvhlFh.App\\Entity\\Employe', NULL, 'Cannot autowire service ".service_locator.rCvhlFh": it needs an instance of "App\\Entity\\Employe" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'employe' => 'App\\Entity\\Employe',
            'entityManager' => '?',
            'validator' => '?',
        ]);
    }
}
