oauth_google_connect:
    path: /connect/google
    controller: HWI\Bundle\OAuthBundle\Controller\ConnectController::connectAction

oauth_google_check:
    path: /connect/google/check
    controller: HWI\Bundle\OAuthBundle\Controller\ConnectController::checkAction


controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
