<?php

namespace ContainerD6iowwV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2shiioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u2shiio' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u2shiio'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\EmployeController::delete' => ['privates', '.service_locator.I3mS6IL', 'get_ServiceLocator_I3mS6ILService', true],
            'App\\Controller\\EmployeController::edit' => ['privates', '.service_locator.I3mS6IL', 'get_ServiceLocator_I3mS6ILService', true],
            'App\\Controller\\EmployeController::index' => ['privates', '.service_locator.JwMuhT7', 'get_ServiceLocator_JwMuhT7Service', true],
            'App\\Controller\\EmployeController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EmployeController::show' => ['privates', '.service_locator.je7oNoj', 'get_ServiceLocator_Je7oNojService', true],
            'App\\Controller\\OffreController::delete' => ['privates', '.service_locator.V6favct', 'get_ServiceLocator_V6favctService', true],
            'App\\Controller\\OffreController::edit' => ['privates', '.service_locator.V6favct', 'get_ServiceLocator_V6favctService', true],
            'App\\Controller\\OffreController::index' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController::inscriptionoffre' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OffreController::show' => ['privates', '.service_locator.0uzROk4', 'get_ServiceLocator_0uzROk4Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\EmployeController:delete' => ['privates', '.service_locator.I3mS6IL', 'get_ServiceLocator_I3mS6ILService', true],
            'App\\Controller\\EmployeController:edit' => ['privates', '.service_locator.I3mS6IL', 'get_ServiceLocator_I3mS6ILService', true],
            'App\\Controller\\EmployeController:index' => ['privates', '.service_locator.JwMuhT7', 'get_ServiceLocator_JwMuhT7Service', true],
            'App\\Controller\\EmployeController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\EmployeController:show' => ['privates', '.service_locator.je7oNoj', 'get_ServiceLocator_Je7oNojService', true],
            'App\\Controller\\OffreController:delete' => ['privates', '.service_locator.V6favct', 'get_ServiceLocator_V6favctService', true],
            'App\\Controller\\OffreController:edit' => ['privates', '.service_locator.V6favct', 'get_ServiceLocator_V6favctService', true],
            'App\\Controller\\OffreController:index' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController:inscriptionoffre' => ['privates', '.service_locator.kjLqtAK', 'get_ServiceLocator_KjLqtAKService', true],
            'App\\Controller\\OffreController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OffreController:show' => ['privates', '.service_locator.0uzROk4', 'get_ServiceLocator_0uzROk4Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\EmployeController::delete' => '?',
            'App\\Controller\\EmployeController::edit' => '?',
            'App\\Controller\\EmployeController::index' => '?',
            'App\\Controller\\EmployeController::new' => '?',
            'App\\Controller\\EmployeController::show' => '?',
            'App\\Controller\\OffreController::delete' => '?',
            'App\\Controller\\OffreController::edit' => '?',
            'App\\Controller\\OffreController::index' => '?',
            'App\\Controller\\OffreController::inscriptionoffre' => '?',
            'App\\Controller\\OffreController::new' => '?',
            'App\\Controller\\OffreController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\EmployeController:delete' => '?',
            'App\\Controller\\EmployeController:edit' => '?',
            'App\\Controller\\EmployeController:index' => '?',
            'App\\Controller\\EmployeController:new' => '?',
            'App\\Controller\\EmployeController:show' => '?',
            'App\\Controller\\OffreController:delete' => '?',
            'App\\Controller\\OffreController:edit' => '?',
            'App\\Controller\\OffreController:index' => '?',
            'App\\Controller\\OffreController:inscriptionoffre' => '?',
            'App\\Controller\\OffreController:new' => '?',
            'App\\Controller\\OffreController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
