<?php

namespace Container9uv6Npx;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMateriellocation2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qAUb40R.App\Entity\Materiellocation' shared service.
     *
     * @return \App\Entity\Materiellocation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.qAUb40R": it needs an instance of "App\\Entity\\Materiellocation" but this type has been excluded in "config/services.yaml".');
    }
}
