<?php

namespace ContainerFXc5ywZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParcelleProprietesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IU.QoY9.App\Entity\ParcelleProprietes' shared service.
     *
     * @return \App\Entity\ParcelleProprietes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.IU.QoY9": it needs an instance of "App\\Entity\\ParcelleProprietes" but this type has been excluded in "config/services.yaml".');
    }
}
