<?php

namespace ContainerVhTBeJa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_FdGL6xjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.fdGL6xj' shared service.
     *
     * @return \App\Controller\CategorieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\AdminController::tablesIndex()": the $categorieRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CategorieRepository". Did you forget to add a use statement?');
    }
}
