<?php

namespace ContainerVhTBeJa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DjkKGKNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DjkKGKN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DjkKGKN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieRepository' => ['privates', '.errored.fdGL6xj', NULL, 'Cannot determine controller argument for "App\\Controller\\AdminController::tablesIndex()": the $categorieRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CategorieRepository". Did you forget to add a use statement?'],
            'materielVenteRepository' => ['privates', 'App\\Repository\\MaterielventeRepository', 'getMaterielventeRepositoryService', true],
        ], [
            'categorieRepository' => '?',
            'materielVenteRepository' => 'App\\Repository\\MaterielventeRepository',
        ]);
    }
}
