<?php

namespace ContainerNRFI1nf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E1sZMAGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E1sZMAG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E1sZMAG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contrat' => ['privates', '.errored..service_locator.E1sZMAG.App\\Entity\\Contrat', NULL, 'Cannot autowire service ".service_locator.E1sZMAG": it needs an instance of "App\\Entity\\Contrat" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'yousignService' => ['privates', 'App\\Service\\YousignService', 'getYousignServiceService', true],
        ], [
            'contrat' => 'App\\Entity\\Contrat',
            'entityManager' => '?',
            'yousignService' => 'App\\Service\\YousignService',
        ]);
    }
}
