<?php

namespace ContainerVnfhxwM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielvente2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wZGs69i.App\Entity\Materielvente' shared service.
     *
     * @return \App\Entity\Materielvente
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wZGs69i": it needs an instance of "App\\Entity\\Materielvente" but this type has been excluded in "config/services.yaml".');
    }
}
