<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPgyrlgJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPgyrlgJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPgyrlgJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPgyrlgJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPgyrlgJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PgyrlgJ',
    'container.build_id' => '1def25c8',
    'container.build_time' => 1739668048,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPgyrlgJ');
