<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ80JtsI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ80JtsI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ80JtsI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ80JtsI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ80JtsI\App_KernelDevDebugContainer([
    'container.build_hash' => 'J80JtsI',
    'container.build_id' => 'aa65f4fc',
    'container.build_time' => 1739040821,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ80JtsI');
