<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNRFI1nf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNRFI1nf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNRFI1nf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNRFI1nf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNRFI1nf\App_KernelDevDebugContainer([
    'container.build_hash' => 'NRFI1nf',
    'container.build_id' => 'c27174ef',
    'container.build_time' => 1741005481,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNRFI1nf');
