<?php

namespace ContainerJPy8E5x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8T8ZnRQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8T8ZnRQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8T8ZnRQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\UtilisateurController::delete' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController::edit' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController::index' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\UtilisateurController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UtilisateurController::show' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\UtilisateurController:delete' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController:edit' => ['privates', '.service_locator.5iifHkm', 'get_ServiceLocator_5iifHkmService', true],
            'App\\Controller\\UtilisateurController:index' => ['privates', '.service_locator.9QfjjfA', 'get_ServiceLocator_9QfjjfAService', true],
            'App\\Controller\\UtilisateurController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UtilisateurController:show' => ['privates', '.service_locator.8NzCy4M', 'get_ServiceLocator_8NzCy4MService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\UtilisateurController::delete' => '?',
            'App\\Controller\\UtilisateurController::edit' => '?',
            'App\\Controller\\UtilisateurController::index' => '?',
            'App\\Controller\\UtilisateurController::new' => '?',
            'App\\Controller\\UtilisateurController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\UtilisateurController:delete' => '?',
            'App\\Controller\\UtilisateurController:edit' => '?',
            'App\\Controller\\UtilisateurController:index' => '?',
            'App\\Controller\\UtilisateurController:new' => '?',
            'App\\Controller\\UtilisateurController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
